module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest', {
      jsc: { parser: { syntax: 'typescript' } },
      module: { type: 'commonjs' },
    }],
  },
  moduleNameMapper: {
    '^better-auth/node$': '<rootDir>/tests/better-auth-node.mock.ts',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  collectCoverageFrom: [
    'src/config/auth.ts',
    'src/config/health.ts',
    'src/middleware/authMiddleware.ts',
    'src/middleware/errors.ts',
    'src/modules/profile/profile.controller.ts',
    'src/modules/profile/profile.routes.ts',
    'src/modules/profile/profile.service.ts',
    'src/modules/recovery/recovery.controller.ts',
    'src/modules/recovery/recovery.routes.ts',
    'src/modules/recovery/recovery.service.ts',
    'src/modules/road-report/road-report.controller.ts',
    'src/modules/road-report/road-report.routes.ts',
    'src/modules/road-report/road-report.service.ts',
    'src/modules/road-report/road-report.validation.ts',
    'src/modules/route-comparison/exposure.service.ts',
    'src/modules/route-comparison/providers/google-routes.provider.ts',
    'src/modules/route-comparison/route-comparison.controller.ts',
    'src/modules/route-comparison/route-comparison.routes.ts',
    'src/modules/route-comparison/route-comparison.service.ts',
    'src/modules/route-comparison/route-comparison.validation.ts',
    'src/modules/route-comparison/weather-advisory.service.ts',
    'src/utils/apiResponse.ts',
  ],
  coverageReporters: ['text', 'html', 'lcov'],
  coverageThreshold: { global: { branches: 85, functions: 95, lines: 95, statements: 95 } },
}
